name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  BuildRelease:
    if: github.ref_name == 'main'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set build type
        id: set-env
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          BUILD_TYPE="DEBUG"

          if [[ "$COMMIT_MSG" == *"pre-release"* ]]; then
            BUILD_TYPE="PRE_RELEASE"
          elif [[ "$COMMIT_MSG" == *"release"* ]]; then
            BUILD_TYPE="RELEASE"
          fi

          echo "SL_BUILD_TYPE=${BUILD_TYPE}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JRE JAR files
        run: |
          chmod +x gradlew
          mkdir out
          ./gradlew jre_lwjgl3glfw:build --no-daemon

      - name: Build Release ${{ matrix.arch }}
        env:
          MOVTERY_KEYSTORE_PASSWORD: ${{ secrets.MOVTERY_KEYSTORE_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assemblerelease -Darch=${{ matrix.arch }}

      - name: Upload Release ${{matrix.arch}}
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: SaltLauncher(Release) ${{ matrix.arch }}
          path: ZalithLauncher/build/outputs/apk/release/*

  BuildDebug:
    if: startsWith(github.ref, 'refs/pull/') || github.ref_name != 'main'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JRE JAR files
        run: |
          chmod +x gradlew
          mkdir out
          ./gradlew jre_lwjgl3glfw:build --no-daemon

      - name: Build Debug ${{matrix.arch}}
        run: |
          chmod +x gradlew
          ./gradlew ZalithLauncher:assembleDebug -Darch=${{ matrix.arch }}

      - name: Upload Debug ${{matrix.arch}}
        uses: actions/upload-artifact@v4
        with:
          name: SaltLauncher(Debug) ${{ matrix.arch }}
          path: ZalithLauncher/build/outputs/apk/debug/*
